# SAM configuration file
version = 0.1

[default.global.parameters]
stack_name = "financial-bot"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "TelegramBotToken=placeholder"

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

# Configurações por ambiente
[dev.deploy.parameters]
stack_name = "financial-bot-dev"
s3_prefix = "financial-bot-dev"
region = "us-east-1"
parameter_overrides = "Environment=dev TelegramBotToken=dev-token-placeholder"

[staging.deploy.parameters]
stack_name = "financial-bot-staging"
s3_prefix = "financial-bot-staging"
region = "us-east-1"
parameter_overrides = "Environment=staging TelegramBotToken=staging-token-placeholder"

[prod.deploy.parameters]
stack_name = "financial-bot-prod"
s3_prefix = "financial-bot-prod"
region = "us-east-1"
parameter_overrides = "Environment=prod TelegramBotToken=prod-token-placeholder"
