AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Financial Categorizer Telegram Bot

Parameters:
  TelegramBotToken:
    Type: String
    Description: Token do bot do Telegram
    NoEcho: true
  
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Ambiente de deployment

Globals:
  Function:
    Timeout: 30
    Runtime: python3.11
    Environment:
      Variables:
        BOT_TOKEN_TELEGRAM: !Ref TelegramBotToken
        ENVIRONMENT: !Ref Environment

Resources:
  # CloudWatch Log Group
  BotLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/financial-bot-${Environment}"
      RetentionInDays: 14

