name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m pytest -q

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [ test ]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install SAM CLI
        run: |
          python -m pip install --upgrade pip
          python -m pip install aws-sam-cli
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Delete existing stack (prod)
        run: |
          sam delete --stack-name financial-bot-prod --region ${{ secrets.AWS_REGION }} --no-prompts || true
          aws cloudformation wait stack-delete-complete --region ${{ secrets.AWS_REGION }} --stack-name financial-bot-prod || true
      - name: SAM build
        working-directory: infra
        run: |
          sam build --template template.yaml --build-dir .aws-sam/build
      - name: SAM deploy (prod)
        working-directory: infra
        run: |
          sam deploy \
            --stack-name financial-bot-prod \
            --resolve-s3 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_IAM \
            --template-file .aws-sam/build/template.yaml \
            --parameter-overrides \
              ParameterKey=Environment,ParameterValue=prod \
              ParameterKey=TelegramBotToken,ParameterValue=${{ secrets.BOT_TOKEN_TELEGRAM }} \
              ParameterKey=GoogleApiKey,ParameterValue=${{ secrets.GOOGLE_API_KEY }} \
              ParameterKey=RepoUrl,ParameterValue=https://github.com/dinero-organizer/financial-categorizer-bot.git


